-- ============================================================================
-- SKEMA LENGKAP & KEBIJAKAN RLS SUPABASE: REAKTOR ESTERIFIKASI
-- ============================================================================
-- Jalankan skrip ini di SQL Editor dashboard Supabase Anda:
-- https://supabase.com/dashboard/project/_/sql

-- 1. TABEL PROFILES (Penyimpanan relasi User Auth & Telegram Chat ID)
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    telegram_chat_id TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Aktifkan RLS pada tabel profiles
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- Kebijakan RLS untuk PROFILES:
-- a) Service Role (Backend API) memiliki akses penuh
DROP POLICY IF EXISTS "Service role can manage all profiles" ON public.profiles;
CREATE POLICY "Service role can manage all profiles"
    ON public.profiles
    FOR ALL
    TO service_role
    USING (true)
    WITH CHECK (true);

-- b) Pengguna terotentikasi (Authenticated User) dapat membaca profil miliknya sendiri
DROP POLICY IF EXISTS "Users can read own profile" ON public.profiles;
CREATE POLICY "Users can read own profile"
    ON public.profiles
    FOR SELECT
    TO authenticated
    USING (auth.uid() = id);

-- c) Pengguna terotentikasi dapat memasukkan (insert) profil miliknya sendiri
DROP POLICY IF EXISTS "Users can insert own profile" ON public.profiles;
CREATE POLICY "Users can insert own profile"
    ON public.profiles
    FOR INSERT
    TO authenticated
    WITH CHECK (auth.uid() = id);

-- d) Pengguna terotentikasi dapat memperbarui (update) profil miliknya sendiri
DROP POLICY IF EXISTS "Users can update own profile" ON public.profiles;
CREATE POLICY "Users can update own profile"
    ON public.profiles
    FOR UPDATE
    TO authenticated
    USING (auth.uid() = id)
    WITH CHECK (auth.uid() = id);


-- 2. TABEL REACTOR_LOGS (Penyimpanan telemetri sensor & riwayat batch)
CREATE TABLE IF NOT EXISTS public.reactor_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stage INT NOT NULL,
    temp NUMERIC NOT NULL,
    rpm NUMERIC NOT NULL,
    vol NUMERIC NOT NULL,
    current NUMERIC NOT NULL DEFAULT 0,
    waktu_lokal TEXT NOT NULL,
    tanggal TEXT NOT NULL,
    batch_id TEXT NOT NULL,
    batch_code TEXT NOT NULL,
    level_detected BOOLEAN DEFAULT FALSE,
    sensor_payload JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    recorded_at TIMESTAMPTZ DEFAULT NOW()
);

-- Index untuk mempercepat query filtering per batch dan pengurutan waktu
CREATE INDEX IF NOT EXISTS idx_reactor_logs_batch_id ON public.reactor_logs (batch_id);
CREATE INDEX IF NOT EXISTS idx_reactor_logs_recorded_at ON public.reactor_logs (recorded_at DESC);

-- Aktifkan RLS pada tabel reactor_logs
ALTER TABLE public.reactor_logs ENABLE ROW LEVEL SECURITY;

-- Kebijakan RLS untuk REACTOR_LOGS:
-- a) Service Role memiliki akses penuh
DROP POLICY IF EXISTS "Service role can manage all logs" ON public.reactor_logs;
CREATE POLICY "Service role can manage all logs"
    ON public.reactor_logs
    FOR ALL
    TO service_role
    USING (true)
    WITH CHECK (true);

-- b) Pengguna terotentikasi dapat membaca semua riwayat log reaktor
DROP POLICY IF EXISTS "Authenticated users can read reactor logs" ON public.reactor_logs;
CREATE POLICY "Authenticated users can read reactor logs"
    ON public.reactor_logs
    FOR SELECT
    TO authenticated
    USING (true);

-- c) Pengguna terotentikasi dapat menambahkan log
DROP POLICY IF EXISTS "Authenticated users can insert reactor logs" ON public.reactor_logs;
CREATE POLICY "Authenticated users can insert reactor logs"
    ON public.reactor_logs
    FOR INSERT
    TO authenticated
    WITH CHECK (true);

-- d) Anon / Publik (jika API frontend mengakses langsung secara publik)
DROP POLICY IF EXISTS "Public can read reactor logs" ON public.reactor_logs;
CREATE POLICY "Public can read reactor logs"
    ON public.reactor_logs
    FOR SELECT
    TO anon
    USING (true);
